# Generated by Django 5.2 on 2025-04-19 09:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, default='profile_pics/default_profile_pic.jpg', null=True, upload_to='profile_pics')),
                ('bio', models.TextField()),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ai_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('humorous', 'Humorous'), ('mentor', 'Mentor-like')], default='friendly', max_length=20)),
                ('ai_response_length', models.CharField(choices=[('short', 'Short (1-2 sentences)'), ('medium', 'Medium (paragraph)'), ('detailed', 'Detailed')], default='medium', max_length=10)),
                ('preferred_domains', models.JSONField(default=['technology', 'science'])),
                ('preferred_response_format', models.CharField(choices=[('paragraph', 'Paragraphs'), ('bullet', 'Bullet Points'), ('step', 'Step-by-Step'), ('tabbed', 'Tabbed View')], default='paragraph', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
