# Generated by Django 5.2 on 2025-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_preferred_language'),
        ('chatapp', '0004_chatmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinned_rooms',
            field=models.ManyToManyField(blank=True, related_name='pinned_by', to='chatapp.chatroom'),
        ),
    ]
