# Generated by Django 5.2 on 2025-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic.jpg', null=True, upload_to='room_images/'),
        ),
    ]
