# Generated by Django 5.2 on 2025-04-19 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chatroom_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
