# Generated by Django 5.1.3 on 2025-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chatmessage_image_chatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
