# Generated by Django 5.2 on 2025-04-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatroom_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatapp.chatmessage'),
        ),
    ]
